authors:
  eilam:
    name: Tamar Eilam
    description: AI-native Systems Researcher
    avatar: https://github.com/eilamt.png
  oliveira:
    name: Fabio A. Oliveira
    description: AI-native Systems Researcher
    avatar: https://github.com/fabolive.png
  factor:
    name: Michael Factor
    description: AI-native Systems Researcher
    avatar: https://github.com/factorm.png
  jgchn:
    name: Jing Chen
    description: AI-native Systems Researcher
    avatar: https://github.com/jgchn.png
  kalantar:
    name: Michael Kalantar
    description: AI-native Systems Researcher
    avatar: https://github.com/kalantar.png
  sriumcp:
    name: Srinivasan Parthasarathy
    description: AI-native Systems Researcher
    avatar: https://github.com/sriumcp.png
  toslali-ibm:
    name: Mert Toslali
    description: AI-native Systems Researcher
    avatar: https://github.com/toslali-ibm.png
  susiejojo:
    name: Dipanwita Guhathakurta
    description: AI-native Systems Researcher
    avatar: https://github.com/susiejojo.png
